# Generated by Django 5.1.6 on 2025-09-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_news_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/news/', verbose_name='Фотография'),
        ),
    ]
