# Generated by Django 5.1.6 on 2025-09-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='Прикрепите скриншот проблемы (необязательно)', null=True, upload_to='Feedback.generate_unique_filename', verbose_name='Скриншот'),
        ),
    ]
