# Generated by Django 5.1.6 on 2025-12-11 19:59

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_feedback_slug_alter_feedback_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='Прикрепите скриншот проблемы', null=True, upload_to=main.models.generate_unique_filename, verbose_name='Скриншот'),
        ),
    ]
