# Generated by Django 5.1.6 on 2025-12-04 14:44

import personal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, help_text='Загрузите фото профиля', null=True, upload_to=personal.models.generate_profile_photo_filename, verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Загрузите фото профиля', null=True, upload_to=personal.models.generate_profile_photo_filename, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
