# Generated by Django 5.1.6 on 2025-12-11 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_doctor_photo_userprofile_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('can_change_email', 'Может изменять email адрес аккаунта')], 'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
    ]
